version: '3'
services:
    nginx:
        build:
            context: .
            dockerfile: Dockerfile-nginx
        ports:
            - 80:80
    uwsgi:
        build:
            context: .
            dockerfile: Dockerfile-uwsgi

