FROM python:3.7-alpine

WORKDIR /usr/src

ENV PYTHONPATH $PYTHONPATH:/usr/src

RUN apk add --update gcc libc-dev linux-headers

RUN pip install uwsgi Flask elasticsearch-dsl

COPY . .

EXPOSE 3031

CMD ["uwsgi", "uwsgi.ini"]

